### ISSUE TITLE
Fix building on sle12

### ISSUE THREAD

**Issue by darix** [openSUSE/mysql-packaging#31]
```
Index: mariadb-101.spec
===================================================================
--- mariadb-101.spec    (revision 42)
+++ mariadb-101.spec    (working copy)
@@ -128,7 +128,7 @@
 BuildRoot:      %{_tmppath}/%{name}-%{version}-build
 %{?systemd_requires}
 # On mariadb we want readline5 and on mysql we use libedit from system
-%if "%{name}" == "mariadb"
+%if "%{name}" == "mariadb" && (0%{?suse_version} != 1315)
 BuildRequires:  readline5-devel
 %else
 BuildRequires:  libedit-devel
```

**Comment by scarabeusiv** [comment]
This should break it on leap which has readline5-devel no?

**Comment by darix** [comment]
On 2015-11-17 11:00:35 -0800, Tomáš Chvátal wrote:
> This should break it on leap which has readline5-devel no?

it actually succeeds but it will use libedit. I needed builds for sle12
to get the exec fix fir mysql_start().

    darix

-- 
           openSUSE - SUSE Linux is my linux
               openSUSE is good for you
                   www.opensuse.org

**Comment by darix** [comment]
tbh ... the logic was probably wrong in any case. and only did by luck
what you expected.

**Comment by darix** [comment]
tbh i would be interested in a matrix for "which readline library do you want to use on which target"

**Comment by darix** [comment]
This should even work on sle11
```
Index: mariadb-101.spec
===================================================================
--- mariadb-101.spec    (revision 43)
+++ mariadb-101.spec    (working copy)
@@ -128,8 +128,12 @@
 BuildRoot:      %{_tmppath}/%{name}-%{version}-build
 %{?systemd_requires}
 # On mariadb we want readline5 and on mysql we use libedit from system
-%if "%{name}" == "mariadb" && (0%{?suse_version} != 1315)
+%if ("%{name}" == "mariadb" ) && ! (( 0%{?suse_version} == 1315 ) && ( ! 0%{?is_opensuse} ))
+%if 0%{?suse_version} >= 1310
 BuildRequires:  readline5-devel
+%else
+BuildRequires:  readline-devel
+%endif
 %else
 BuildRequires:  libedit-devel
 %endif
```

**Comment by kstreitova** [comment]
It should be like that (for mysql-packaging git)
 
| Product  | Library   |
|----------|-----------|
| SLE12    | libedit   |
| 13.1     | readline5 |
| 13.2     | readline5 |
| Factory  | readline5 |
| Leap     | readline5 |

As we are not interested in SLE11 here I would simplify the condition to:

```
 %{?systemd_requires}
 # On mariadb we want readline5 and on mysql we use libedit from system
-%if "%{name}" == "mariadb" && (0%{?suse_version} != 1315)
+%if ("%{name}" == "mariadb" ) && ! (( 0%{?suse_version} == 1315 ) && ( ! 0%{?is_opensuse} ))
 BuildRequires:  readline5-devel
 %else
 BuildRequires:  libedit-devel
 %endif
 ```

**Comment by kstreitova** [comment]
Submitted by https://github.com/openSUSE/mysql-packaging/commit/cc5b28e3d11c207d787098ffd27b9857478e122c

Closing.
