### ISSUE TITLE
Wait longer during startup, if mysqld is still running

### ISSUE THREAD

**Issue by adrium** [openSUSE/mysql-packaging#52]
I pushed a commit for old the old init scripts (openSUSE <= 13.2). It might help someone, or it might be used to create a new support update: adrium@12ccf8a

The wait time for the DB server to start is 30 seconds. In case of data corruption, recovery needs to kick in. However, when the scripts exits after 30 seconds, the server is killed prematurely during recovery.

Looking at [common/mysql-systemd-helper](../blob/master/common/mysql-systemd-helper#L147), the wait time seems to be 60 seconds. But is this enough?

**Comment by darix** [comment]
clean way would be sd_notify support for mariadb.

**Comment by kstreitova** [comment]
Fixed in sr#563277. The type of the service was changed to "notify" and you can now control the time to wait for start-up/stop via "TimeoutSec=" option.

Closing.
